# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcku5p-ffvb676-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/fpga_xku5p.cache/wt [current_project]
set_property parent.project_path /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/fpga_xku5p.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/fpga_xku5p.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/cpu_cfig.h
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_dmi_define.h
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_define.h
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/sysmap.h
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_cfig.h
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_cfig.h
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_cfig.h
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/addr_map.svh
}
set_property file_type "Verilog Header" [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/cpu_cfig.h]
set_property is_global_include true [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/cpu_cfig.h]
set_property file_type "Verilog Header" [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_dmi_define.h]
set_property is_global_include true [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_dmi_define.h]
set_property file_type "Verilog Header" [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_define.h]
set_property is_global_include true [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_define.h]
set_property file_type "Verilog Header" [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/sysmap.h]
set_property is_global_include true [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/sysmap.h]
set_property file_type "Verilog Header" [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_cfig.h]
set_property is_global_include true [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_cfig.h]
set_property file_type "Verilog Header" [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_cfig.h]
set_property is_global_include true [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_cfig.h]
set_property file_type "Verilog Header" [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_cfig.h]
set_property is_global_include true [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_cfig.h]
set_property file_type "Verilog Header" [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/addr_map.svh]
set_property is_global_include true [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/addr_map.svh]
read_verilog -library xil_defaultlib -sv {
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/apb/apb2reg/apb2reg.sv
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/apb/apb_sub_system.sv
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/axi2apb_wrap.sv
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/axi_bus.sv
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/axi_interconnect_wrap.sv
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/axi_slave128_warp.sv
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/c906_wrap.sv
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/soc.sv
}
read_verilog -library xil_defaultlib {
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/common/rtl/BUFGCE.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/biu/rtl/aq_biu_apbif.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/biu/rtl/aq_biu_read_channel.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/biu/rtl/aq_biu_req_arbiter.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/biu/rtl/aq_biu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/biu/rtl/aq_biu_write_channel.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/biu/rtl/aq_biu_wt_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/aq_core.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_cache_inst.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_ext_csr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_fence_inst.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_float_csr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_hpcp_csr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_info_csr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_iui.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_lpmd.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_prtc_csr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_regs.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_rst_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_special.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_trap_csr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cp0/rtl/aq_cp0_vector_inst.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/aq_cpuio_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_dcache_data_array.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_dcache_dirty_array.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_dcache_tag_array.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_dcache_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_cdc.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_cdc_lvl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_cdc_pulse.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_dbginfo.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_iie_trigger.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_m_iie_all.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_mcontrol.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_mcontrol_output_select.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_pcfifo.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/dtu/rtl/aq_dtu_trigger_module.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/aq_f_spsram_1024x16.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/aq_f_spsram_1024x64.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/aq_f_spsram_128x8.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/aq_f_spsram_2048x32.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/aq_f_spsram_256x59.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/aq_f_spsram_64x58.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/aq_f_spsram_64x88.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/aq_f_spsram_64x98.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_double_add.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_double_cmp_max.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_double_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_double_round.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_double_special.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_double_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_lop_s1_sb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_scalar_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_shift_sub_h_double.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fadd_shift_sub_single.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_falu_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_falu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fcnvt_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fcnvt_double.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fcnvt_dtos_d.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fcnvt_ftoi_d.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fcnvt_scalar_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fcnvt_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fcnvt_xtoh_sh.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_denorm_shift.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_double.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_double_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_pack.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_prepare.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_right_shift.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_round.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_scalar_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_scalar_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_special.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_srt.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfdsu/rtl/aq_fdsu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_fspu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmu/rtl/aq_hpcp_adder_sel.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmu/rtl/aq_hpcp_cnt.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmu/rtl/aq_hpcp_cntinten_reg.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmu/rtl/aq_hpcp_cntof_reg.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmu/rtl/aq_hpcp_event.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmu/rtl/aq_hpcp_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_expand_32.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_id_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_id_decd.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_id_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_id_gpr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_id_gpr_gated_reg.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_id_split.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_id_wbt.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_id_wbt_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/idu/rtl/aq_idu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_bht.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_bht_array.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_btb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_btb_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_ibuf.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_ibuf_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_ibuf_pop_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_icache.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_icache_data_array.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_icache_tag_array.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_ipack.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_ipack_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_pcgen.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_pre_decd.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_pred.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_ras.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_ras_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_ifu_vec.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/aq_iu_addr_gen.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/aq_iu_alu.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/aq_iu_bju.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/aq_iu_div.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/aq_iu_div_shift2_kernel.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/aq_iu_mul.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/aq_iu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_left_shift_64.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_ag.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_amo_alu.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_amr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_arb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_dc.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_dtif.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_icc.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_lfb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_lfb_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_lm.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_mcic.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_pfb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_pfb_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_rdl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_stb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_stb_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_lsu_vb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_arb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_jtlb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_jtlb_data_array.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_jtlb_tag_array.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_plru.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_ptw.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_regs.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_sysmap.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_sysmap_hit.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_tlboper.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_utlb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_utlb_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_mmu_utlb_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/clk/rtl/aq_mp_clk_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/rst/rtl/aq_mp_rst_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmp/rtl/aq_pmp_acc.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmp/rtl/aq_pmp_comp_hit.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmp/rtl/aq_pmp_regs.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/pmp/rtl/aq_pmp_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_prio.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/rtu/rtl/aq_rtu_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/rtu/rtl/aq_rtu_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/rtu/rtl/aq_rtu_int.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/rtu/rtl/aq_rtu_rbus.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/rtu/rtl/aq_rtu_retire.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/rtu/rtl/aq_rtu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/rtu/rtl/aq_rtu_wb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_spsram_1024x16.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_spsram_1024x64.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_spsram_128x8.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_spsram_2048x32.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/ifu/rtl/aq_spsram_256x59.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_spsram_64x58.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_spsram_64x88.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/mmu/rtl/aq_spsram_64x98.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/aq_sysio_kid.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/aq_sysio_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/aq_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfalu/rtl/aq_vdsp_64_bit_ff1.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vdiv/rtl/aq_vdsp_8_bit_ff1.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_frac_mult.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_frac_shift_double.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_lza_double.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_mult.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_mult_double.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_multiplier_53x27_partial.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_special_judge_double.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/aq_vfmau_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vidu/rtl/aq_vidu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vidu/rtl/aq_vidu_vid_ctrl_fp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vidu/rtl/aq_vidu_vid_dp_fp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vidu/rtl/aq_vidu_vid_gpr_fp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vidu/rtl/aq_vidu_vid_gpr_reg_fp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vidu/rtl/aq_vidu_vid_split_fp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vidu/rtl/aq_vidu_vid_wbt.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vidu/rtl/aq_vidu_vid_wbt_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_vlsu_data_trans.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_vlsu_ld_align_buffer.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_vlsu_lsu_if.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_vlsu_rot_data.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_vlsu_st_align_buffer.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_vlsu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_vlsu_vtb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/lsu/rtl/aq_vlsu_vtb_entry.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vdsp/rtl/aq_vpu_fwd_wb_rbus.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vdsp/rtl/aq_vpu_group_unit.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vdsp/rtl/aq_vpu_srcv_type.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vdsp/rtl/aq_vpu_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vdsp/rtl/aq_vpu_viq_dp.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/axi/axi_interconnect/arbiter.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/axi/axi2apb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/axi/axi_interconnect/axi_interconnect.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/booth_code_33_bit.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/vfmau/rtl/booth_code_54_bit.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/clint/rtl/clint_func.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/clint/rtl/clint_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/csky_apb_1tox_matrix.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/fpga/rtl/fpga_ram.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/clk/rtl/gated_clk_cell.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/iu/rtl/multiplier_33x33_partial.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/cpu/rtl/openC906.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/soc/per_clk_gen.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_32to1_arb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_arb_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_granu2_arb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_granu_arb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_hart_arb.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_hreg_busif.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_int_kid.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_kid_busif.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/plic/rtl/plic_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/axi/axi_interconnect/priority_encoder.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/common/rtl/sync_level2level.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_apb_master.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dm.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dm_pulse_sync.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dm_sync_dff.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_dm_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_dmi.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dmi_pulse_sync.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_dmi_rst_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dmi_sync_dff.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_dmi_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dtm_chain.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dtm_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dtm_idr.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dtm_io.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_dtm_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/common/tdt_gated_clk_cell.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/debug/tdt_sba_axi.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/c906_core/tdt/rtl/top/tdt_top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/apb/apb2uart/uart.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/apb/apb2uart/uart_apb_reg.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/apb/apb2uart/uart_baud_gen.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/apb/apb2uart/uart_ctrl.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/apb/apb2uart/uart_receive.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/apb/apb2uart/uart_trans.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/top.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/axi/axi2sram/f_spsram_16384x128.v
  /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/rtl/peripheral/axi/axi2sram/axi_slave128.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/constrs/top.xdc
set_property used_in_implementation false [get_files /home/zfh/Desktop/soc_workspace/soc_c906_v1.1/fpga_xku5p/constrs/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xcku5p-ffvb676-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_no_debug_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
